#!/bin/bash
../scaling_plot_categorical.py ./results.xls --title_prefix "Versions" --file_prefix "versions" --worksheet_name "categorical" --walltime_units "Seconds" --plot_width 10 --filter "include" --category_column "version" --baseline_category "baseline"
