#!/bin/bash
scaling_plot results.xls --title_prefix "Weak Scaling" --file_prefix "weak" --compute_element_name "threads" --worksheet_name "weak" --walltime_units "Seconds" --plot_width 10 --speedup_max 25 --filter "include" --weak
